spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update #dev
    properties:
      hibernate:
        format_sql: true
      show-sql: true

springDoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: hardship-service

logging:
  level:
    org.springframework.web.servlet.resource: OFF # fix favicon 500 error

