spring:
  profiles:
    active: local # overridden by ECS env var in prod
  jpa:
    open-in-view: false # stop session open for entire Http request, force load everything in service layer
    show-sql: false # show sql in console (P6Spy instead)
    properties:
      hibernate:
        format_sql: false # format sql (P6Spy instead)

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: hardship-service





